In [1]:
import os
current_path = os.getcwd()
folder = "MA"
path =  folder.join(current_path.split(folder)[:-1])+folder
os.chdir(path)

In [2]:
import numpy as np
import pandas as pd

In [3]:
from Repair.Dimensionality_Reduction.RobustPCA.vadetis import HuberLoss, MRobustPCA

delta = 1
n_components = 1

loss = HuberLoss(delta)
v_pca = MRobustPCA(n_components,loss)

In [4]:
m = np.array([[6,3,3],[-2,2,2 ],[-7,1,-5],[-3,1,-5],[2,-4,2]])
m

array([[ 6,  3,  3],
       [-2,  2,  2],
       [-7,  1, -5],
       [-3,  1, -5],
       [ 2, -4,  2]])

In [5]:
transform  = v_pca.fit_transform(m)

x_prime = v_pca.inverse_transform(transform)
x_prime

matrix
\begin{bmatrix}
6.0 & 3.0 & 3.0\\
-2.0 & 2.0 & 2.0\\
-7.0 & 1.0 & -5.0\\
-3.0 & 1.0 & -5.0\\
2.0 & -4.0 & 2.0\\
\end{bmatrix}
weights_1
\begin{bmatrix}
0.2\\
0.2\\
0.2\\
0.2\\
0.2\\
\end{bmatrix}
mean_1
\begin{bmatrix}
-0.8\\
0.6\\
-0.6\\
\end{bmatrix}
X^c_1
\begin{bmatrix}
6.8 & 2.4 & 3.6\\
-1.2 & 1.4 & 2.6\\
-6.2 & 0.4 & -4.4\\
-2.2 & 0.4 & -4.4\\
2.8 & -4.6 & 2.6\\
\end{bmatrix}
C_1
\begin{bmatrix}
-0.79 & 0.03 & -0.61\\
\end{bmatrix}
errors
\begin{bmatrix}
2.92\\
3.13\\
0.38\\
2.14\\
4.51\\
\end{bmatrix}
weights_2
\begin{bmatrix}
0.15\\
0.14\\
0.43\\
0.2\\
0.09\\
\end{bmatrix}
mean_2
\begin{bmatrix}
-2.78\\
0.96\\
-2.22\\
\end{bmatrix}
X^c_2
\begin{bmatrix}
8.78 & 2.04 & 5.22\\
0.78 & 1.04 & 4.22\\
-4.22 & 0.04 & -2.78\\
-0.22 & 0.04 & -2.78\\
4.78 & -4.96 & 4.22\\
\end{bmatrix}
C_2
\begin{bmatrix}
-0.8 & -0.01 & -0.6\\
\end{bmatrix}
errors
\begin{bmatrix}
2.2\\
3.07\\
0.33\\
2.09\\
5.07\\
\end{bmatrix}
weights_3
\begin{bmatrix}
0.18\\
0.13\\
0.41\\
0.19\\
0.08\\
\end{bmatri

array([[ 5.81537326,  2.36856305,  3.39164676],
       [-0.13992698,  1.59775771, -0.65848921],
       [-6.82567727,  0.73240888, -5.20539644],
       [-4.12164823,  1.08239628, -3.36641522],
       [ 2.03912096,  1.87979585,  0.82345798]])

In [6]:
from Repair.Dimensionality_Reduction.RobustPCA.Robust_pca_estimator import Robust_PCA_estimator

r_pca = Robust_PCA_estimator(n_components,delta=1,center=True)


m
r_pca.reduce(m)

In [7]:
m

array([[ 6,  3,  3],
       [-2,  2,  2],
       [-7,  1, -5],
       [-3,  1, -5],
       [ 2, -4,  2]])

In [8]:

m_r_prime = r_pca.reduce(m)

[-0.8  0.6 -0.6]
X_centered
 [[ 6.8  2.4  3.6]
 [-1.2  1.4  2.6]
 [-6.2  0.4 -4.4]
 [-2.2  0.4 -4.4]
 [ 2.8 -4.6  2.6]]
errors [2.92108005 3.12867613 0.3824798  2.14408243 4.50909441]
[-2.78318445  0.95550564 -2.22207733]
X_centered
 [[ 8.78318445  2.04449436  5.22207733]
 [ 0.78318445  1.04449436  4.22207733]
 [-4.21681555  0.04449436 -2.77792267]
 [-0.21681555  0.04449436 -2.77792267]
 [ 4.78318445 -4.95550564  4.22207733]]
errors [2.20394455 3.07133945 0.33420205 2.09092168 5.06606657]
[-2.43130234  1.10024376 -2.03021776]
X_centered
 [[ 8.43130234  1.89975624  5.03021776]
 [ 0.43130234  0.89975624  4.03021776]
 [-4.56869766 -0.10024376 -2.96978224]
 [-0.56869766 -0.10024376 -2.96978224]
 [ 4.43130234 -5.10024376  4.03021776]]
errors [1.67386724 3.098368   0.33737455 2.06504385 5.4290385 ]
[-1.9876849   1.23047651 -1.78284839]
X_centered
 [[ 7.9876849   1.76952349  4.78284839]
 [-0.0123151   0.76952349  3.78284839]
 [-5.0123151  -0.23047651 -3.21715161]
 [-1.0123151  -0.23047651 -3.

In [9]:
m_r_prime-x_prime

array([[ 9.81277826e-05, -4.55416223e-06, -1.56444966e-04],
       [ 2.32866828e-04, -6.30981193e-06, -2.30517629e-04],
       [ 2.73847042e-04, -2.25555853e-05, -3.88682636e-04],
       [ 2.03138136e-04, -2.29919512e-05, -3.61531202e-04],
       [ 1.62812470e-04, -8.35361766e-06, -2.17529044e-04]])

In [10]:
m,m_r_prime,x_prime


(array([[ 6,  3,  3],
        [-2,  2,  2],
        [-7,  1, -5],
        [-3,  1, -5],
        [ 2, -4,  2]]),
 array([[ 5.81547139,  2.3685585 ,  3.39149031],
        [-0.13969412,  1.5977514 , -0.65871973],
        [-6.82540343,  0.73238633, -5.20578512],
        [-4.12144509,  1.08237329, -3.36677675],
        [ 2.03928378,  1.87978749,  0.82324045]]),
 array([[ 5.81537326,  2.36856305,  3.39164676],
        [-0.13992698,  1.59775771, -0.65848921],
        [-6.82567727,  0.73240888, -5.20539644],
        [-4.12164823,  1.08239628, -3.36641522],
        [ 2.03912096,  1.87979585,  0.82345798]]))