In [1]:
import os
current_path = os.getcwd()
folder = "MA"
path =  folder.join(current_path.split(folder)[:-1])+folder
os.chdir(path)

In [2]:
import numpy as np
import pandas as pd

In [3]:

from Repair.Dimensionality_Reduction.RobustPCA.vadetis.loss import HuberLoss

from Repair.Dimensionality_Reduction.RobustPCA.vadetis.m_est_rpca import MRobustPCA

delta = 1
n_components = 1

loss = HuberLoss(delta)
v_pca = MRobustPCA(n_components,loss)

In [4]:
m = np.array([[6,3,3],[-2,2,2 ],[-7,1,-5],[-3,1,-5],[2,-4,2]])
m

array([[ 6,  3,  3],
       [-2,  2,  2],
       [-7,  1, -5],
       [-3,  1, -5],
       [ 2, -4,  2]])

In [5]:
transform  = v_pca.fit_transform(m)

x_prime = v_pca.inverse_transform(transform)
x_prime

matrix
\begin{bmatrix*}[r]
6.0 & 3.0 & 3.0\\
-2.0 & 2.0 & 2.0\\
-7.0 & 1.0 & -5.0\\
-3.0 & 1.0 & -5.0\\
2.0 & -4.0 & 2.0\\
\end{bmatrix*}
W_1 = 
\begin{bmatrix*}[r]
0.2\\
0.2\\
0.2\\
0.2\\
0.2\\
\end{bmatrix*}
M_1 = 
\begin{bmatrix*}[r]
-0.8\\
0.6\\
-0.6\\
\end{bmatrix*}
\mathbf{X}^c_1 = 
\begin{bmatrix*}[r]
6.8 & 2.4 & 3.6\\
-1.2 & 1.4 & 2.6\\
-6.2 & 0.4 & -4.4\\
-2.2 & 0.4 & -4.4\\
2.8 & -4.6 & 2.6\\
\end{bmatrix*}
\mathbf{X}^c_1*W_1^1/2 = 
\begin{bmatrix*}[r]
3.04 & 1.07 & 1.61\\
-0.54 & 0.63 & 1.16\\
-2.77 & 0.18 & -1.97\\
-0.98 & 0.18 & -1.97\\
1.25 & -2.06 & 1.16\\
\end{bmatrix*}
C_1
\begin{bmatrix*}[r]
-0.79 & 0.03 & -0.61\\
\end{bmatrix*}
C*C^T_1
\begin{bmatrix*}[r]
0.62 & -0.02 & 0.48\\
-0.02 & 0.0 & -0.02\\
0.48 & -0.02 & 0.38\\
\end{bmatrix*}
X*C*C^T_1
\begin{bmatrix*}[r]
5.93 & -0.2 & 4.61\\
0.48 & -0.02 & 0.37\\
-6.0 & 0.2 & -4.66\\
-3.51 & 0.12 & -2.73\\
3.1 & -0.11 & 2.41\\
\end{bmatrix*}
X^c_1-X^r_1
\begin{bmatrix*}[r]
0.87 & 2.6 & -1.01\\
-1.68 & 1.42 & 2.23\\
-0.2 & 0

array([[ 5.81537326,  2.36856305,  3.39164676],
       [-0.13992698,  1.59775771, -0.65848921],
       [-6.82567727,  0.73240888, -5.20539644],
       [-4.12164823,  1.08239628, -3.36641522],
       [ 2.03912096,  1.87979585,  0.82345798]])

In [6]:
from Repair.Dimensionality_Reduction.RobustPCA.Robust_pca_estimator import Robust_PCA_estimator

r_pca = Robust_PCA_estimator(n_components,delta=1,center=True)


m
r_pca.reduce(m)

In [7]:
m

array([[ 6,  3,  3],
       [-2,  2,  2],
       [-7,  1, -5],
       [-3,  1, -5],
       [ 2, -4,  2]])

In [8]:

m_r_prime = r_pca.reduce(m)

[-0.8  0.6 -0.6]
X_centered
 [[ 6.8  2.4  3.6]
 [-1.2  1.4  2.6]
 [-6.2  0.4 -4.4]
 [-2.2  0.4 -4.4]
 [ 2.8 -4.6  2.6]]
errors [2.92108005 3.12867613 0.3824798  2.14408243 4.50909441]
[-2.78318445  0.95550564 -2.22207733]
X_centered
 [[ 8.78318445  2.04449436  5.22207733]
 [ 0.78318445  1.04449436  4.22207733]
 [-4.21681555  0.04449436 -2.77792267]
 [-0.21681555  0.04449436 -2.77792267]
 [ 4.78318445 -4.95550564  4.22207733]]
errors [2.20394455 3.07133945 0.33420205 2.09092168 5.06606657]
[-2.43130234  1.10024376 -2.03021776]
X_centered
 [[ 8.43130234  1.89975624  5.03021776]
 [ 0.43130234  0.89975624  4.03021776]
 [-4.56869766 -0.10024376 -2.96978224]
 [-0.56869766 -0.10024376 -2.96978224]
 [ 4.43130234 -5.10024376  4.03021776]]
errors [1.67386724 3.098368   0.33737455 2.06504385 5.4290385 ]
[-1.9876849   1.23047651 -1.78284839]
X_centered
 [[ 7.9876849   1.76952349  4.78284839]
 [-0.0123151   0.76952349  3.78284839]
 [-5.0123151  -0.23047651 -3.21715161]
 [-1.0123151  -0.23047651 -3.

In [9]:
m_r_prime-x_prime

array([[ 9.81277826e-05, -4.55416223e-06, -1.56444966e-04],
       [ 2.32866828e-04, -6.30981193e-06, -2.30517629e-04],
       [ 2.73847042e-04, -2.25555853e-05, -3.88682636e-04],
       [ 2.03138136e-04, -2.29919512e-05, -3.61531202e-04],
       [ 1.62812470e-04, -8.35361766e-06, -2.17529044e-04]])

In [10]:
m,m_r_prime,x_prime


(array([[ 6,  3,  3],
        [-2,  2,  2],
        [-7,  1, -5],
        [-3,  1, -5],
        [ 2, -4,  2]]),
 array([[ 5.81547139,  2.3685585 ,  3.39149031],
        [-0.13969412,  1.5977514 , -0.65871973],
        [-6.82540343,  0.73238633, -5.20578512],
        [-4.12144509,  1.08237329, -3.36677675],
        [ 2.03928378,  1.87978749,  0.82324045]]),
 array([[ 5.81537326,  2.36856305,  3.39164676],
        [-0.13992698,  1.59775771, -0.65848921],
        [-6.82567727,  0.73240888, -5.20539644],
        [-4.12164823,  1.08239628, -3.36641522],
        [ 2.03912096,  1.87979585,  0.82345798]]))

In [17]:
from Repair.Dimensionality_Reduction.CDrec.CDrecclassifier import CD_Rec_estimator

cd_estim = CD_Rec_estimator(truncation=1,delta=1)
print("a")
print(cd_estim.reduce(m))
cd_estim = CD_Rec_estimator(truncation=1,delta=2)
print("a")
print(cd_estim.reduce(m))
cd_estim = CD_Rec_estimator(truncation=1,delta=0.01)
print("a")
print(cd_estim.reduce(m))


a
11.55056480635632
11.514561144127974
11.492032556551031
11.473187441128427
11.457901771329011
11.445559519059518
11.435561677135444
11.427424867556988
11.42077146476506
11.415307235267697
11.410801930117586
11.407074249059779
11.404045232578225
11.402970007145617
11.402590164203335
11.402450795048043
11.40239890281461
11.402379474871513
11.40237218642764
11.402369450100167
11.402368422507688
11.402368036569523
11.402367891615356
11.402367837171404
[[ 3.9416491   0.20178896  4.75190113]
 [-0.4254371   0.63703223  0.31609527]
 [-6.30816579  1.22333117 -5.65920294]
 [-4.34896828  1.02806882 -3.66917586]
 [ 1.82665394  0.4125788   2.6036248 ]]
a
18.404129043093302
18.328251949430644
18.323440173637714
18.32280440566563
18.322673257193962
18.322643743435464
18.322637148105517
18.322635699298516
18.322635385406592
18.322635318070454
[[ 4.05186392  0.24544804  4.60055037]
 [-0.22698146  0.6914657   0.16008138]
 [-6.05127083  1.29857711 -5.88420722]
 [-4.13541314  1.09887222 -3.89598238]
 [ 

In [12]:
v_pca.errors_

array([10.77607842, 10.48811775, 10.32322838, 10.21674926, 10.14359588,
       10.11470511, 10.11442191, 10.1144067 , 10.11440535])